version: '3.9'

services:
  api:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app

  worker:
    volumes:
      - .:/app
    command: ["celery", "-A", "app.common.celery:celery_app", "worker", "--loglevel=info"]

  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
