services:
  app:
    build: .
    image: predictmma-image
    container_name: predictmma-container
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__/
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - redis

  celery:
    image: predictmma-image
    container_name: celery-container
    command: celery -A app.common.celery:celery_app worker --loglevel=info --pool=solo
    volumes:
      - .:/app
      - /app/__pycache__/
    environment:
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
      app:
        condition: service_started
